import test from 'node:test';
import assert from 'node:assert/strict';
import { CameraRig, easeInOut } from '../src/math.js';
import { normalizeData } from '../src/data.js';
import { planJourney, LocalMemory } from '../src/journey.js';
import { atmosphereFor, makeNoise } from '../src/atmosphere.js';
import { shaderSources, ConstellationRenderer } from '../src/renderer.js';
const nodes=Array.from({length:30},(_,i)=>Object.freeze({index:i,x:(i-15)*60,y:i%5*3,z:-60+i,w:60,h:40,font:6,seed:i,mask:i%2+1,comment:{id:'id-'+i,author:'author-'+i%5,text:'An exact original comment '+i}}));
const storage=()=>{const m=new Map();return {getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v),all:()=>[...m.values()]};};
const data={account:'test',comments:nodes.map(n=>n.comment)};
test('a wander visits at most seven actual, unique nodes',()=>{const r=planJourney(nodes);assert.equal(r.length,7);assert.equal(new Set(r.map(n=>n.index)).size,7);assert.ok(r.every(n=>nodes.includes(n)));});
test('wander order is deterministic for the same collection and history',()=>assert.deepEqual(planJourney(nodes),planJourney(nodes)));
test('wander does not mutate frozen nodes or input order',()=>{const s=JSON.stringify(nodes);planJourney(nodes);assert.equal(s,JSON.stringify(nodes));});
test('wander respects mood and author constraints',()=>{const r=planJourney(nodes,{mood:1,author:'author-0'});assert.ok(r.length>0);assert.ok(r.every(n=>n.mask&1&&n.comment.author==='author-0'));});
test('empty wander is safe',()=>assert.deepEqual(planJourney([],{}),[]));
test('short collections never fabricate extra stops',()=>assert.equal(planJourney(nodes.slice(0,2)).length,2));
test('wander makes forward spatial progress instead of teleporting across the name',()=>{const r=planJourney(nodes);assert.ok(r.every((n,i)=>!i||n.x>=r[i-1].x));});
test('fresh memory keeps no marks',()=>{const m=new LocalMemory(storage());m.useCollection(data);assert.equal(m.visited.size,0);assert.equal(m.kept.size,0);});
test('visited and kept IDs persist and can be recovered independently',()=>{const s=storage(),a=new LocalMemory(s);a.useCollection(data);a.visit('id-1');a.toggleKeep('id-2');const b=new LocalMemory(s);b.useCollection(data);assert.deepEqual([...b.visited],['id-1']);assert.deepEqual([...b.kept],['id-2']);});
test('browser memory never stores the original comment text or authors',()=>{const s=storage(),m=new LocalMemory(s);m.useCollection(data);m.visit('id-1');m.toggleKeep('id-2');assert.ok(!s.all().join('').includes('exact original'));assert.ok(!s.all().join('').includes('author-'));});
test('unkeep and forget affect only local marks',()=>{const m=new LocalMemory(storage());m.useCollection(data);const before=JSON.stringify(data);assert.equal(m.toggleKeep('id-1'),true);assert.equal(m.toggleKeep('id-1'),false);m.visit('id-2');m.forget();assert.equal(m.visited.size,0);assert.equal(JSON.stringify(data),before);});
test('different collections do not borrow visited state',()=>{const m=new LocalMemory(storage());m.useCollection(data);m.visit('id-1');m.useCollection({comments:[{id:'else'}]});assert.equal(m.visited.size,0);m.useCollection(data);assert.ok(m.visited.has('id-1'));});
test('blocked or quota-full browser storage leaves the session usable',()=>{const m=new LocalMemory({getItem(){throw new Error('denied');},setItem(){throw new Error('full');}});m.useCollection(data);m.visit('id-1');assert.equal(m.available,false);assert.ok(m.visited.has('id-1'));assert.equal(m.toggleKeep('id-1'),true);});
test('no storage is reported as session-only rather than persistent',()=>{const m=new LocalMemory(undefined);m.useCollection(data);m.visit('id-1');assert.equal(m.available,false);});
test('malformed saved data is ignored',()=>{const s={getItem:()=>'{wrong',setItem:()=>{}};const m=new LocalMemory(s);m.useCollection(data);assert.equal(m.kept.size,0);});
test('implicit IDs preserve identical comments without silently deduplicating them',()=>{const d=normalizeData([{text:'Same.',author:'A'},{text:'Same.',author:'A'}]);assert.equal(d.comments.length,2);assert.notEqual(d.comments[0].id,d.comments[1].id);});
test('flight starts from the current camera, not a new layout',()=>{const rig=new CameraRig(1440,900),start={...rig.current};rig.flyTo({x:700,y:60,z:200});assert.deepEqual(rig.current,start);assert.ok(rig.flight);});
test('flight completes exactly at the destination under irregular frame times',()=>{const rig=new CameraRig(1440,900),end={x:700,y:60,z:200};rig.flyTo(end);for(let i=0;i<300;i++)rig.tick(i%3?.011:.04);assert.deepEqual(rig.current,end);assert.equal(rig.flight,null);});
test('camera flight is finite, continuous, and above the near plane',()=>{const rig=new CameraRig(1440,900);rig.flyTo({x:1100,y:-350,z:80});let last={...rig.current};for(let i=0;i<150;i++){rig.tick(1/60);assert.ok(Object.values(rig.current).every(Number.isFinite));assert.ok(rig.current.z>=78);assert.ok(Math.abs(rig.current.x-last.x)<65);last={...rig.current};}});
test('a new gesture cancels a camera flight immediately',()=>{const rig=new CameraRig(1440,900);rig.flyTo({x:800,y:50,z:120});rig.tick(.04);const before={...rig.current};rig.pan(10,0);assert.equal(rig.flight,null);assert.equal(rig.current.z,before.z);});
test('reduced motion can jump to the exact camera target',()=>{const rig=new CameraRig(390,844),end={x:200,y:80,z:200};rig.flyTo(end);rig.tick(0,true);assert.deepEqual(rig.current,end);assert.equal(rig.flight,null);});
test('pan inertia decays and remains inside world bounds',()=>{const rig=new CameraRig(390,844);rig.coast(9000,-9000);for(let i=0;i<400;i++)rig.tick(1/60);assert.ok(Math.abs(rig.target.x)<=1320);assert.ok(Math.abs(rig.target.y)<=470);assert.ok(Math.hypot(rig.velocity.x,rig.velocity.y)<.11);});
test('cinematic easing has exact endpoints and is monotone',()=>{assert.equal(easeInOut(0),0);assert.equal(easeInOut(1),1);let prev=0;for(let i=0;i<=100;i++){const n=easeInOut(i/100);assert.ok(n>=prev);prev=n;}});
test('world atmosphere is deterministic and does not change comment nodes',()=>{const before=JSON.stringify(nodes);assert.deepEqual(atmosphereFor(nodes),atmosphereFor(nodes));assert.equal(JSON.stringify(nodes),before);});
test('cloud billows remain behind the word field',()=>{const a=atmosphereFor(nodes);assert.ok(a.clouds.every(c=>c.z<-300));assert.ok(a.stars.every(s=>Number.isFinite(s.z)));});
test('noise is repeatable and remains bounded',()=>{const a=makeNoise(31),b=makeNoise(31);for(let i=-20;i<20;i++){const n=a(i*.31,i*.49);assert.equal(n,b(i*.31,i*.49));assert.ok(n>=0&&n<=1);}});
test('all four production shader pairs are exposed to the native compilation test',()=>{assert.deepEqual(Object.keys(shaderSources),['words','stars','clouds','lines']);for(const p of Object.values(shaderSources)){assert.ok(p.vertex.startsWith('#version 300 es'));assert.ok(p.fragment.startsWith('#version 300 es'));}});

test('an import during graphics loss replaces the logical collection queued for restoration',async()=>{const renderer={lost:true,lastLayout:{nodes:['old']}};const incoming={nodes:['new']};await ConstellationRenderer.prototype.setLayout.call(renderer,incoming);assert.equal(renderer.lastLayout,incoming);});
